### PR TITLE
Explicitly mention contribution requirements

### PR DESCRIPTION
**Pull request by sebakerckhof**
Apparently, contributing to Meteor (https://github.com/meteor/meteor/pull/7858#issuecomment-257818452) requires you to follow the airbnb style guide, which was not really clear.

### CODE REVIEW

**Comment by lorensr** [comment]
Right place, since Contributing.md links here https://github.com/meteor/meteor/blob/devel/Contributing.md#submitting-pull-requests

Wording - what about "It's the style guide used for Meteor itself."? or Meteor internals, or ...

**Comment by lorensr** [comment]
Let's change Contributing.md instead of linking here. @benjamn should we ask contributors to use Airbnb style guide with ES6 extensions? cc @abernix

**Comment by abernix** [comment]
I'd agree.  Although we might have to be careful with saying ES6 as there still parts of the tool which cannot use ES6.  It seems that linking contributing to here was a temporary measure to deal with the discontinuation of the Meteor Wiki.  Instead of adding the extra wording here in the guide (which is intended to refer to apps), it might be best to just [directly state here in Contributing.md](https://github.com/meteor/meteor/blame/7bd2c57b1dd35f92284c59cc9300f65c3c0cbf4a/Contributing.md#L233), something along the lines of:

* New contributions should follow the [Airbnb style guide](https://github.com/airbnb/javascript) as closely as possible.
* Do not change/update code that doesn't directly relate to the feature/bug that you're working on.
* Use a short and helpful commit title (max 80 characters)
* Use a commit description which clearly explains the change and reference related issues by number (e.g. `Fixes #9999`)

**Comment by abernix** [comment]
[`Contributing.md`](https://github.com/meteor/meteor/blob/devel/Contributing.md#submitting-pull-requests) no longer points here thanks to https://github.com/meteor/meteor/commit/36b4fae9e51eea2a25fb25ab26742940ffe1bfd7 and because of the existence of the new [`Development.md`](https://github.com/meteor/meteor/blob/devel/Development.md) (PR https://github.com/meteor/meteor/pull/8267).

I think it's safe to close this now without merging.  Thank you for suggesting this in the first place, @sebakerckhof.  Issues such as this were certainly inspiration for me to work on `Development.md`.  If you have any further suggestions/ideas (or objections to closing this), do tell! 😄 (Though, maybe they should go into the new document!)

**Pull request closed without merging**
