### PR TITLE
German translation for Introduction

### PR DESCRIPTION
**Pull request by lightningboss**
I've translated the first file, index.md, for the Meteor Guide. In general, I am satisfied with the translation, but there are some words or phrases that are hard or not to translate correctly.

Before merging this PR, please let at least two others check this translation for typos and misconceptions. I will comment on the parts that should be improved.

### CODE REVIEW

**Comment by tmeasday** [comment]
It would be good to get more eyes on this but in the meantime, I've merged and it should soon be available at guide.meteor.com/tde

**Comment by tmeasday** [comment]
Oh, you'll need to merge current `master` into your branch for the deployment to work. Perhaps ping me when you've done that @lightningboss?

**Comment by lightningboss** [comment]
I have merged `master` into `translation-de` in my fork.

**Comment by lightningboss** [comment]
@nerdmed wants to review the translation.

**Comment by tmeasday** [comment]
@lightningboss can you send a second PR? I can't merge it from here it seems.

**Pull request merged**
