### PR TITLE
Added paragraph on TypeScript conditional imports.

### PR DESCRIPTION
**Pull request by realyze**
TODO:

- [x] If this is a significant change, update [CHANGELOG.md](https://github.com/meteor/guide/blob/master/CHANGELOG.md)
- [x] Use `<h2 id="foo">` instead of `## Foo` for headers
- [x] Leave a blank line after each header

### CODE REVIEW

**Comment by realyze** [comment]
https://github.com/meteor/meteor/issues/8428

**Comment by abernix** [comment]
This looks great!  Thank you for taking the time do this (and research it!).

Did you have any additional feelings about this update after reading the information about dynamic imports in https://github.com/meteor/meteor/pull/8327#issuecomment-284160678?

If not, I'm happy to merge this!

**Comment by realyze** [comment]
Thanks @abernix . The bottomline of https://github.com/meteor/meteor/pull/8327#issuecomment-284160678 is basically that adding dynamic `import` to TypeScript will be quite a challenge for the TS team so it probably won't happen anytime soon (if at all).

When Meteor 1.5 is released, I guess it will make sense to update this by mentioning the `module.dynamicImport` workaround.

**Comment by realyze** [comment]
BTW I also wrote a short post about it which explains it with a Meteor code example [on my blog](http://ideasintosoftware.com/typescript-conditional-imports/) but I didn't want to link to my personal blog from the guide. Dunno if that's frowned upon or legit...you tell me, I guess. :-)

**Comment by abernix** [comment]
@realyze If it's relevant and we don't have a good place to put it right now (both of these things seem true), go for it – I approve of [the link you've provided](http://ideasintosoftware.com/typescript-conditional-imports/).

I will make the disclaimer that at some point and time in the future, I could see us having a have a dedicated TypeScript section where this would fit very well (although, hopefully at some point we can make this exception obsolete). :smile:

**Comment by realyze** [comment]
@abernix Cool, I've updated the patch.

Having a dedicated (and much larger, yes :) ) TS section would be awesome. It certainly appears TypeScript's adoption is increasing quite rapidly and I believe having an easy to follow and readable guide for TS would be encouraging to new Meteor users. There definitely are some gotchas when working with Meteor/TS combo.

**Comment by lorensr** [comment]
Thanks @realyze ! 😊

**Comment by michaeljota** [comment]
FYI: TS 2.4 add supports for Dynamic Imports :+1:

**Pull request merged**
