### PR TITLE
Translation es: Index

### PR DESCRIPTION
**Pull request by hedaro**
I translated the Index.md file, which are for the 1.2 versión.
I tried to translate all technical terms the best way i could, but i think some could be improved, like **client connected**. There are a few terms i left untranslated because i don't know any technical equivalent in spanish. I'll add them if anyone knows the right translation.
Some of these terms are:
- Full stack
- Data on the wire
- Pull request

I left the terms **issues** and **docs** untranslated because they refer to sections of a site (github issues and meteor docs).
I tested all texts with a spell checker, so orthography shouldn't be an issue. Still any corrections and grammar suggestions are appreciated.

### CODE REVIEW

**Comment by tmeasday** [comment]
Thanks @hedaro! Can you merge current `master` into your branch, and we'll get a deployment going?

**Comment by hedaro** [comment]
@tmeasday done.

**Comment by tmeasday** [comment]
Hmm, I think maybe you'll need to send another PR, I can't seem to merge that.

**Comment by hedaro** [comment]
I'm gonna be watching #499, because i did the same thing for the spanish branch, so if that's not the way to go then we first need to figure things out.
It'd help to know exactly what is expected from our branches/forks to get the deployment to work.

**Comment by tmeasday** [comment]
Hey @hedaro, basically we just need the changes to `circle.yml` that are on `master`. But it's probably good to merge `master` into your branch every now and then to avoid the untranslated files going out of date.

**Pull request merged**
