### PR TITLE
Replace practicalmeteor:mocha with meteortesting:mocha

### PR DESCRIPTION
**Pull request by toinevk**
Per https://github.com/meteor/guide/issues/691, replacing practicalmeteor:mocha with meteortesting:mocha. Given the similarities this was a simple find and replace.

### CODE REVIEW

**Comment by abernix** [comment]
Anyone watching have any objections to this?

**Comment by serut** [comment]
Yeap ! you should not let practicalmeteor:sinon and practicalmeteor:chai in the guide if you remove practicalmeteor:mocha. Moreover, this is wrong : "It displays the test results in the browser in a Mocha test reporter:" as meteortesting only display clients tests in the report.

**Comment by abernix** [comment]
@serut:

> Moreover, this is wrong : "It displays the test results in the browser in a Mocha test reporter:" as meteortesting only display clients tests in the report.

What you're saying is true (that the browser will only show client tests and the server test will be shown in the console), but this appears to have been wrong in the guide both before and after this PR, correct?

> you should not let practicalmeteor:sinon and practicalmeteor:chai in the guide if you remove practicalmeteor:mocha.

Can you explain why you're making that mandate?  I ask since both `practicalmeteor:sinon` and `practicalmeteor:chai` are just older implementations of the npm versions of the `sinon` and `chai` testing libraries and should have nothing to do with the actual test running (which `practicalmeteor:mocha` _does_).  I agree that they should be updated (they are unnecessary).

I agree with your suggestions, but it seems like both of them could be done in a separate PR (which would be appreciated if you have time!)

**Comment by serut** [comment]
> What you're saying is true (that the browser will only show client tests and the server test will be shown in the console), but this appears to have been wrong in the guide both before and after this PR, correct?

No, practicalmeteor:mocha was displaying both server and client tests. The screenshot [available here](https://guide.meteor.com/testing.html#driver-packages) is a real one (in watch mode):

Meteor guide report

This PR should bring an updated version of the screenshot, as these 2 tools are not isofunctional.

> Can you explain why you're making that mandate?

It looks like `practicalmeteor:chai` and `practicalmeteor:sinon` are looking for the same version of `coffeescript` that `practicalmeteor:mocha`. The main goal of removing `practicalmeteor:mocha` is to remove dependency to `coffeescript@1`, so we can't promote any `practicalmeteor:*` package anymore.  

Here is the error message if you integrate another module that requires `coffeescript 2` : 
```
Conflict: Constraint coffeescript@1.0.3 is not satisfied by coffeescript 2.0.1_1.
Constraints on package "coffeescript":
* coffeescript@=2.0.1_1 <- top level
* coffeescript@1.0.4 <- arillo:flow-router-helpers 0.5.2
* coffeescript@1.0.4 <- zimme:active-route 2.3.2
* coffeescript@1.0.4 <- tap:i18n 1.8.2
* coffeescript@1.0.4 <- softwarerero:accounts-t9n 1.3.9
* coffeescript@1.0.3 <- practicalmeteor:chai 2.1.0_1
* coffeescript@1.0.3 <- practicalmeteor:sinon 1.14.1_2
```
[source](https://github.com/meteor/meteor/pull/9107#issuecomment-338285855)

Of course, you can accept this PR and iterate again and again, that's just my recommendation.

**Comment by serut** [comment]
@toinevk 
Don't forget to upgrade the sinon syntax, as you are upgrading sinon V1.14 to V5.0 : 
```
    sinon.stub(FlowRouter, 'getParam', () => listId);
```
becomes
```
    sinon.stub(FlowRouter, 'getParam').returns(listId);
```
Hopefully, there is only 1 or 2 occurences of sinon in that file.

And I had no change while upgrading chai, so after that LSTM :balloon: !

**Comment by toinevk** [comment]
Thanks @serut I have tested and is passing. Should be ready to merge.

**Comment by serut** [comment]
@abernix feel free to merge that PR.

**Comment by abernix** [comment]
Thanks to all, especially @toinevk for opening this originally!

**Pull request merged**
