### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by robfallows**
Please read the commit notes. There's some code I can't get to work as documented.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/meteor/guide/pull/172%23issuecomment-166696127%22%2C%20%22https%3A//github.com/meteor/guide/pull/172%23issuecomment-166697744%22%2C%20%22https%3A//github.com/meteor/guide/pull/172%23issuecomment-166698254%22%2C%20%22https%3A//github.com/meteor/guide/pull/172%23issuecomment-166698333%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/meteor/guide/pull/172%23issuecomment-166696127%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Taking%20a%20look%20at%20this%20now%21%22%2C%20%22created_at%22%3A%20%222015-12-22T18%3A22%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%2C%20%7B%22body%22%3A%20%22As%20for%20events%2C%20this%20syntax%20%28without%20your%20added%20colon%29%20should%20definitely%20work.%20We%27re%20using%20the%20same%20syntax%20basically%20everywhere%20in%20the%20todos%20example%20app%2C%20for%20example%20here%3A%20https%3A//github.com/meteor/todos/blob/a43b92b5baa58ac5c14860ab4de3d1ddda0add62/packages/lists-show/lists-show.js%23L97%5Cr%5Cn%5Cr%5CnYou%20can%20check%20that%20it%20works%20by%20cloning%20the%20app%20and%20editing%20the%20list%20title.%22%2C%20%22created_at%22%3A%20%222015-12-22T18%3A31%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20also%20just%20verified%20that%20the%20attribute%20helper%20that%20returns%20an%20object%20works%20as%20well...%20do%20you%20have%20an%20example%20of%20an%20app%20where%20it%20doesn%27t%20work%3F%22%2C%20%22created_at%22%3A%20%222015-12-22T18%3A34%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%27s%20weird%20that%20these%20things%20aren%27t%20working%20for%20you%20-%20perhaps%20if%20you%20post%20an%20app%20I%20can%20try%20out%2C%20we%20can%20identify%20what%20is%20different%20between%20them.%20I%27m%20running%20totally%20normal%20Meteor%201.2.1.%22%2C%20%22created_at%22%3A%20%222015-12-22T18%3A34%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/meteor/guide/pull/172#issuecomment-166696127'>General Comment</a></b>
- <a href='https://github.com/stubailo'></a> Taking a look at this now!
- <a href='https://github.com/stubailo'></a> As for events, this syntax (without your added colon) should definitely work. We're using the same syntax basically everywhere in the todos example app, for example here: https://github.com/meteor/todos/blob/a43b92b5baa58ac5c14860ab4de3d1ddda0add62/packages/lists-show/lists-show.js#L97
You can check that it works by cloning the app and editing the list title.
- <a href='https://github.com/stubailo'></a> I also just verified that the attribute helper that returns an object works as well... do you have an example of an app where it doesn't work?
- <a href='https://github.com/stubailo'></a> It's weird that these things aren't working for you - perhaps if you post an app I can try out, we can identify what is different between them. I'm running totally normal Meteor 1.2.1.

<a href='https://www.codereviewhub.com/meteor/guide/pull/172?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/meteor/guide/pull/172?approve=1'></a>&nbsp;<a href='https://github.com/meteor/guide/pull/172'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by stubailo** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/meteor/guide/pull/172'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by stubailo** [comment]
Taking a look at this now!

**Comment by stubailo** [comment]
As for events, this syntax (without your added colon) should definitely work. We're using the same syntax basically everywhere in the todos example app, for example here: https://github.com/meteor/todos/blob/a43b92b5baa58ac5c14860ab4de3d1ddda0add62/packages/lists-show/lists-show.js#L97

You can check that it works by cloning the app and editing the list title.

**Comment by stubailo** [comment]
I also just verified that the attribute helper that returns an object works as well... do you have an example of an app where it doesn't work?

**Comment by stubailo** [comment]
It's weird that these things aren't working for you - perhaps if you post an app I can try out, we can identify what is different between them. I'm running totally normal Meteor 1.2.1.

**Comment by robfallows** [comment]
Cannot replicate the issues I reported. Closing this PR.

**Pull request closed without merging**
