### PR TITLE
Added an example on how to work with subdomains and meta tags

### PR DESCRIPTION
**Pull request by juho**
TODO:

- [x] If this is a significant change, update [CHANGELOG.md](https://github.com/meteor/guide/blob/master/CHANGELOG.md)
- [x] Use `<h2 id="foo">` instead of `## Foo` for headers
- [x] Leave a blank line after each header

### CODE REVIEW

**Comment by juho** [comment]
The example code is based on a night's hacking but has been working fine for us as a slightly modified version. I tried to let the comments do the explaining.

**Comment by abernix** [comment]
My main hesitation to merging this is the length.  Other than that, I think it would be a great addition.

**Comment by StorytellerCZ** [comment]
@juho Can you please sign the CLA, then we can move forward in getting this in.

**Comment by StorytellerCZ** [comment]
I'm closing this since we don't have signed CLA.

**Comment by juho** [comment]
Hi @StorytellerCZ, I've missed the notification as the original PR was from 2017- I've signed the CLA

**Comment by StorytellerCZ** [comment]
I think this is something that should be added to the examples repo instead of guide: https://github.com/meteor/examples

**Comment by filipenevola** [comment]
Hi @juho Meteor now has server-render package that would handle this in a better way.

Please take a look here https://docs.meteor.com/packages/server-render.html

thank for your PR but unfortunately it's not up-to-date anymore :(

**Pull request closed without merging**
