### PR TITLE
Testing (Tinytest)

### PR DESCRIPTION
**Pull request by robfallows**
I've been working on (what started as) a PR for the `tinytest` README. However, it may be worthy of consideration for the Meteor Guide, so I have made some small changes to fit in with the style of the example Routing section.

There is still work to do around "How do I Test ...?".
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/meteor/guide/pull/18%23issuecomment-146748253%22%2C%20%22https%3A//github.com/meteor/guide/pull/18%23issuecomment-151304604%22%2C%20%22https%3A//github.com/meteor/guide/pull/18%23issuecomment-151309971%22%2C%20%22https%3A//github.com/meteor/guide/pull/18%23issuecomment-151321458%22%2C%20%22https%3A//github.com/meteor/guide/pull/18%23issuecomment-152436510%22%2C%20%22https%3A//github.com/meteor/guide/pull/18%23issuecomment-158524921%22%2C%20%22https%3A//github.com/meteor/guide/pull/18%23issuecomment-158821692%22%2C%20%22https%3A//github.com/meteor/guide/pull/18%23issuecomment-160048418%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/meteor/guide/pull/18%23issuecomment-146748253%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20think%20this%20should%20be%20split%20between%20two%2C%20or%20maybe%20three%20guides%2C%20but%20putting%20together%20the%20content%20is%20a%20great%20first%20step.%5Cr%5Cn%5Cr%5Cn1.%20The%20API%20docs%20for%20TinyTest%20%28the%20list%20of%20methods%20and%20arguments%29%20should%20probably%20go%20in%20docs.meteor.com%2C%20or%20in%20the%20README%20if%20we%20can%27t%20fit%20them%20in%20the%20docs%20site%5Cr%5Cn2.%20The%20part%20about%20setting%20up%20package%20tests%20should%20go%20in%20the%20guide%20about%20writing%20packages%5Cr%5Cn3.%20The%20part%20about%20synchronous%20and%20async%20tests%20would%20probably%20go%20in%20the%20testing%20guide%2C%20but%20it%20remains%20to%20be%20seen%20if%20we%20should%20recommend%20TinyTest%20at%20all.%20How%20is%20that%20Mocha%20testing%20package%20doing%3F%5Cr%5Cn%5Cr%5CnHonestly%20having%20a%20custom%20test%20API%20kinda%20sucks%2C%20I%20wonder%20if%20the%20Mocha%20package%20testing%20thing%20by%20Velocity%20works%20well.%22%2C%20%22created_at%22%3A%20%222015-10-09T03%3A46%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20have%20done%20a%20package%20testing%20implementation%20for%20Jasmine%20in%20the%20package%20sanjo%3Ajasmine.%20It%20works%20in%20the%20same%20way%20as%20package%20testing%20with%20Tinytest.%20But%20you%20get%20a%20more%20powerful%20and%20widely%20used%20testing%20framework%20%28Jasmine%29.%20The%20%5Bgetting%20started%20is%20located%20here%5D%28https%3A//dash.readme.io/project/velocity/v1.0/docs/jasmine-testing-a-meteor-package%29.%5Cr%5Cn%5Cr%5CnMike%20has%20initially%20done%20the%20package%20testing%20implementation%20for%20Mocha%2C%20but%20he%20is%20not%20very%20actively%20maintaining%20the%20package.%20That%20said%2C%20the%20package%20testing%20implementation%20that%20I%20have%20in%20sanjo%3Ajasmine%20can%20be%20easily%20applied%20to%20Mocha.%20The%20topic%20Mocha%20vs.%20Jasmine%20is%20another%20debate%20%3A-D%20I%20think%20both%20are%20better%20options%20then%20Tinytest.%5Cr%5Cn%5Cr%5CnFeel%20free%20to%20ask%20me%20any%20questions%20about%20Velocity.%20I%27m%20probably%20the%20person%20with%20the%20deepest%20knowledge%20about%20it.%20%3B-%29%22%2C%20%22created_at%22%3A%20%222015-10-26T22%3A36%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/727955%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Sanjo%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40Sanjo%20do%20you%20have%20any%20reference%20examples%20of%20packages%20tested%20with%20Jasmine%3F%22%2C%20%22created_at%22%3A%20%222015-10-26T23%3A07%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40stubailo%20Right%20now%20I%20only%20have%20this%20very%20basic%20package%3A%20https%3A//github.com/xolvio/meteor-jasmine/tree/master/test-app/packages/package-to-test.%20There%20are%20many%20examples%20of%20using%20Jasmine%20in%20the%20Jasmine%20documentation%3A%20http%3A//jasmine.github.io/2.3/introduction.html.%20You%20can%20just%20use%20them%20in%20the%20test%20files.%22%2C%20%22created_at%22%3A%20%222015-10-27T00%3A19%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/727955%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Sanjo%22%7D%7D%2C%20%7B%22body%22%3A%20%22So%20this%20is%20great%20content%20for%20tinytest.%20I%27m%20not%20planning%20on%20documenting%20that%20in%20the%20guide%20right%20now.%20%40stubailo%20do%20you%20think%20we%20should%20move%20this%20stuff%20to%20the%20readme%20of%20tinytest%3F%22%2C%20%22created_at%22%3A%20%222015-10-30T06%3A01%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/132554%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tmeasday%22%7D%7D%2C%20%7B%22body%22%3A%20%22In%20case%20it%20helps%2C%20I%27ve%20created%20a%20package%20that%20uses%20Tinytest%20underneath%20but%20gives%20us%20an%20API%20similar%20to%20jasmine/mocha.%20It%27s%20still%20an%20early%20version%2C%20but%20I%20think%20it%20could%20grow%20to%20support%20all%20of%20Tinytest%27s%20features%20%28currently%20not%20supported%3A%20addAsync%29%20it%20also%20doesn%27t%20change%20tinytest%27s%20assert%20function%2C%20so%20we%20can%20just%20use%20the%20list%20of%20methods%20from%20the%20docs.%5Cr%5Cn%5Cr%5Cnhere%27s%20the%20package%3A%20%5Bsmithy%3Adescribe%5D%28https%3A//atmospherejs.com/smithy/describe%29%5Cr%5Cn%40stubailo%20%40tmeasday%20I%27d%20love%20to%20get%20your%20feedback%20on%20it%20%3A%29%22%2C%20%22created_at%22%3A%20%222015-11-20T21%3A14%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/21358%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/paolo%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40paolo%20that%20seems%20super%20useful%2C%20and%20would%20have%20made%20my%20life%20when%20testing%20with%20tinytest%20much%20easier.%5Cr%5Cn%5Cr%5CnOTOH%20I%20think%20we%20basically%20decided%20it%20would%20be%20better%20to%20try%20and%20play%20nicer%20with%20the%20existing%20test%20frameworks%20that%20are%20out%20there%2C%20which%20is%20why%20we%20are%20doing%20the%20guide%20using%20various%20Mocha%20packages%20and%20using%20Mocha%20reporters.%22%2C%20%22created_at%22%3A%20%222015-11-23T00%3A18%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/132554%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tmeasday%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40tmeasday%20%40stubailo%20%20thanks%20for%20the%20comment%2C%20I%20did%20tried%20practicalmeteor%3Amocha%2C%20and%20I%20think%20it%27s%20a%20great%20package%2C%20but%20I%20had%20some%20problems%20with%20it%27s%20web%20reporter%2C%20particularly%20on%20re-runs%20after%20code%20changes.%5Cr%5Cn%2A%2AThe%20more%20I%20use%20tinytest%2C%20the%20more%20I%20like%20it%2A%2A%2C%20test%20run%20fast%2C%20it%27s%20reporter%20is%20actually%20quite%20powerful%2C%20we%20can%20select%20a%20subset%20of%20tests%20and%20only%20those%20will%20be%20executed%20on%20code%20changes%2C%20and%20there%20are%20some%20debug%20facilities%20as%20well%20%28I%20haven%27t%20tried%20those%20deeply%20enough%20to%20comment%20though...%29.%5Cr%5Cn%5Cr%5CnSo%2C%20the%20history%20behind%20this%20package%20is%20that%20we%20were%20using%20mike%3Amocha%20in%20a%20couple%20of%20projects%2C%20as%20you%20may%20know%2C%20even%20when%20velocity%20was%20%2A%2Aon%2A%2A%2C%20it%20lacked%20attention%2C%20so%20we%20decided%20to%20migrate%20to%20a%20packages%20based%20app%20and%20use%20tinytest%2C%20rewriting%20all%20the%20tests%20we%20had%20was%20going%20to%20be%20challenging%2C%20so%20I%20wanted%20an%20easy%20way%20to%20migrate%20those%20tests%2C%20that%27s%20when%20%5Bsmithy%3Adescribe%5D%28https%3A//atmospherejs.com/smithy/describe%29%20was%20born.%5Cr%5Cn%5Cr%5CnI%27ve%20recently%20released%20v1.0.0%2C%20with%20a%20much%20more%20complete%20%5BReadme%5D%28https%3A//github.com/paolo/smithy-describe/blob/develop/Readme.md%29%2C%20Async%20support%2C%20sinon%2C%20chai%20and%20a%20couple%20of%20helpers%20for%20async%20exception%20handling.%20It%27s%20API%20is%20very%20similar%20to%20mocha%2C%20which%20allowed%20an%20easy%20transition%20on%20the%20projects%20I%20mentioned.%5Cr%5Cn%5Cr%5CnI%27d%20be%20great%20it%20this%20package%20could%20be%20considered%20and%20improved%20so%20it%20makes%20into%20the%20Meteor%20guide%2C%20since%20all%20mdg%20packages%20are%20tested%20with%20tinytest%2C%20I%20guess%20it%20will%20still%20be%20available%20and%20used.%5Cr%5Cn%5Cr%5CnOf%20course%2C%20I%20can%20understand%20if%20the%20Meteor%20guide%20decides%20to%20go%20with%20a%20different%20solution.%20%22%2C%20%22created_at%22%3A%20%222015-11-27T05%3A47%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/21358%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/paolo%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/meteor/guide/pull/18#issuecomment-146748253'>General Comment</a></b>
- <a href='https://github.com/stubailo'></a> I think this should be split between two, or maybe three guides, but putting together the content is a great first step.
1. The API docs for TinyTest (the list of methods and arguments) should probably go in docs.meteor.com, or in the README if we can't fit them in the docs site
2. The part about setting up package tests should go in the guide about writing packages
3. The part about synchronous and async tests would probably go in the testing guide, but it remains to be seen if we should recommend TinyTest at all. How is that Mocha testing package doing?
Honestly having a custom test API kinda sucks, I wonder if the Mocha package testing thing by Velocity works well.
- <a href='https://github.com/Sanjo'></a> I have done a package testing implementation for Jasmine in the package sanjo:jasmine. It works in the same way as package testing with Tinytest. But you get a more powerful and widely used testing framework (Jasmine). The [getting started is located here](https://dash.readme.io/project/velocity/v1.0/docs/jasmine-testing-a-meteor-package).
Mike has initially done the package testing implementation for Mocha, but he is not very actively maintaining the package. That said, the package testing implementation that I have in sanjo:jasmine can be easily applied to Mocha. The topic Mocha vs. Jasmine is another debate :-D I think both are better options then Tinytest.
Feel free to ask me any questions about Velocity. I'm probably the person with the deepest knowledge about it. ;-)
- <a href='https://github.com/stubailo'></a> @Sanjo do you have any reference examples of packages tested with Jasmine?
- <a href='https://github.com/Sanjo'></a> @stubailo Right now I only have this very basic package: https://github.com/xolvio/meteor-jasmine/tree/master/test-app/packages/package-to-test. There are many examples of using Jasmine in the Jasmine documentation: http://jasmine.github.io/2.3/introduction.html. You can just use them in the test files.
- <a href='https://github.com/tmeasday'></a> So this is great content for tinytest. I'm not planning on documenting that in the guide right now. @stubailo do you think we should move this stuff to the readme of tinytest?
- <a href='https://github.com/paolo'></a> In case it helps, I've created a package that uses Tinytest underneath but gives us an API similar to jasmine/mocha. It's still an early version, but I think it could grow to support all of Tinytest's features (currently not supported: addAsync) it also doesn't change tinytest's assert function, so we can just use the list of methods from the docs.
here's the package: [smithy:describe](https://atmospherejs.com/smithy/describe)
@stubailo @tmeasday I'd love to get your feedback on it :)
- <a href='https://github.com/tmeasday'></a> @paolo that seems super useful, and would have made my life when testing with tinytest much easier.
OTOH I think we basically decided it would be better to try and play nicer with the existing test frameworks that are out there, which is why we are doing the guide using various Mocha packages and using Mocha reporters.
- <a href='https://github.com/paolo'></a> @tmeasday @stubailo  thanks for the comment, I did tried practicalmeteor:mocha, and I think it's a great package, but I had some problems with it's web reporter, particularly on re-runs after code changes.
**The more I use tinytest, the more I like it**, test run fast, it's reporter is actually quite powerful, we can select a subset of tests and only those will be executed on code changes, and there are some debug facilities as well (I haven't tried those deeply enough to comment though...).
So, the history behind this package is that we were using mike:mocha in a couple of projects, as you may know, even when velocity was **on**, it lacked attention, so we decided to migrate to a packages based app and use tinytest, rewriting all the tests we had was going to be challenging, so I wanted an easy way to migrate those tests, that's when [smithy:describe](https://atmospherejs.com/smithy/describe) was born.
I've recently released v1.0.0, with a much more complete [Readme](https://github.com/paolo/smithy-describe/blob/develop/Readme.md), Async support, sinon, chai and a couple of helpers for async exception handling. It's API is very similar to mocha, which allowed an easy transition on the projects I mentioned.
I'd be great it this package could be considered and improved so it makes into the Meteor guide, since all mdg packages are tested with tinytest, I guess it will still be available and used.
Of course, I can understand if the Meteor guide decides to go with a different solution.

<a href='https://www.codereviewhub.com/meteor/guide/pull/18?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/meteor/guide/pull/18?approve=1'></a>&nbsp;<a href='https://github.com/meteor/guide/pull/18'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by stubailo** [comment]
I think this should be split between two, or maybe three guides, but putting together the content is a great first step.

1. The API docs for TinyTest (the list of methods and arguments) should probably go in docs.meteor.com, or in the README if we can't fit them in the docs site
2. The part about setting up package tests should go in the guide about writing packages
3. The part about synchronous and async tests would probably go in the testing guide, but it remains to be seen if we should recommend TinyTest at all. How is that Mocha testing package doing?

Honestly having a custom test API kinda sucks, I wonder if the Mocha package testing thing by Velocity works well.

**Comment by Sanjo** [comment]
I have done a package testing implementation for Jasmine in the package sanjo:jasmine. It works in the same way as package testing with Tinytest. But you get a more powerful and widely used testing framework (Jasmine). The [getting started is located here](https://dash.readme.io/project/velocity/v1.0/docs/jasmine-testing-a-meteor-package).

Mike has initially done the package testing implementation for Mocha, but he is not very actively maintaining the package. That said, the package testing implementation that I have in sanjo:jasmine can be easily applied to Mocha. The topic Mocha vs. Jasmine is another debate :-D I think both are better options then Tinytest.

Feel free to ask me any questions about Velocity. I'm probably the person with the deepest knowledge about it. ;-)

**Comment by stubailo** [comment]
@Sanjo do you have any reference examples of packages tested with Jasmine?

**Comment by Sanjo** [comment]
@stubailo Right now I only have this very basic package: https://github.com/xolvio/meteor-jasmine/tree/master/test-app/packages/package-to-test. There are many examples of using Jasmine in the Jasmine documentation: http://jasmine.github.io/2.3/introduction.html. You can just use them in the test files.

**Comment by tmeasday** [comment]
So this is great content for tinytest. I'm not planning on documenting that in the guide right now. @stubailo do you think we should move this stuff to the readme of tinytest?

**Comment by paolo** [comment]
In case it helps, I've created a package that uses Tinytest underneath but gives us an API similar to jasmine/mocha. It's still an early version, but I think it could grow to support all of Tinytest's features (currently not supported: addAsync) it also doesn't change tinytest's assert function, so we can just use the list of methods from the docs.

here's the package: [smithy:describe](https://atmospherejs.com/smithy/describe)
@stubailo @tmeasday I'd love to get your feedback on it :)

**Comment by tmeasday** [comment]
@paolo that seems super useful, and would have made my life when testing with tinytest much easier.

OTOH I think we basically decided it would be better to try and play nicer with the existing test frameworks that are out there, which is why we are doing the guide using various Mocha packages and using Mocha reporters.

**Comment by paolo** [comment]
@tmeasday @stubailo  thanks for the comment, I did tried practicalmeteor:mocha, and I think it's a great package, but I had some problems with it's web reporter, particularly on re-runs after code changes.
**The more I use tinytest, the more I like it**, test run fast, it's reporter is actually quite powerful, we can select a subset of tests and only those will be executed on code changes, and there are some debug facilities as well (I haven't tried those deeply enough to comment though...).

So, the history behind this package is that we were using mike:mocha in a couple of projects, as you may know, even when velocity was **on**, it lacked attention, so we decided to migrate to a packages based app and use tinytest, rewriting all the tests we had was going to be challenging, so I wanted an easy way to migrate those tests, that's when [smithy:describe](https://atmospherejs.com/smithy/describe) was born.

I've recently released v1.0.0, with a much more complete [Readme](https://github.com/paolo/smithy-describe/blob/develop/Readme.md), Async support, sinon, chai and a couple of helpers for async exception handling. It's API is very similar to mocha, which allowed an easy transition on the projects I mentioned.

I'd be great it this package could be considered and improved so it makes into the Meteor guide, since all mdg packages are tested with tinytest, I guess it will still be available and used.

Of course, I can understand if the Meteor guide decides to go with a different solution.

**Comment by tmeasday** [comment]
Hey @paolo, I think we'd rather people expended effort on improving our mocha support rather than tinytest at this stage. I just think it fits better with our general movement to try and be doing what other people outside of Meteor are doing.

I'm not quite sure what the best way to promote describe to people who are keen on tinytest are but I definitely would like to figure out a way how.

**Comment by tmeasday** [comment]
@robfallows - can you open this as a PR against https://github.com/meteor/meteor/blob/devel/packages/tinytest/README.md ?

I promise it will be quickly accepted ;)

Perhaps you can mention `smithy:describe` in there somewhere also?

**Comment by robfallows** [comment]
Done :smile:

**Pull request closed without merging**
