### PR TITLE
Add eslint-import-resolver-meteor to style guide doc.

### PR DESCRIPTION
**Pull request by N0bl3**
Add eslint-import-resolver-meteor to style guide documentation.
Removed eslint configuration which where handled incorrectly (either reporting all path or none).

### CODE REVIEW

**Comment by tmeasday** [comment]
This looks great. Can we get a corresponding PR to https://github.com/meteor/todos ?

**Comment by N0bl3** [comment]
Yes I will do it. Please tell me if i can put it somewhere else. I want to
contribute to Meteor while i learn from it.

2016-06-27 0:39 GMT+02:00 Tom Coleman <notifications@github.com>:

**Comment by tmeasday** [comment]
Thanks!

**Comment by N0bl3** [comment]
I feel like i should reintroduce the meteor/eventmap-params rule or find a solution to this error. What do you think?

**Comment by tmeasday** [comment]
Oh, agreed. I didn't realise we got rid of that. Can we put it back?

**Comment by N0bl3** [comment]
Did you do it or should i do it since i know what's wrong exactly

**Comment by tmeasday** [comment]
Sure, send a PR!

**Pull request merged**
