### PR TITLE
Add projects section of meteor.com to "Other Meteor resources"

### PR DESCRIPTION
**Pull request by mbrookes**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/meteor/guide/pull/186%23issuecomment-169828474%22%2C%20%22https%3A//github.com/meteor/guide/pull/186%23issuecomment-169828588%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/meteor/guide/pull/186%23issuecomment-169828474%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Incidentally%2C%20that%20page%20has%20a%20%5C%22Follow%20these%20links%20to%20explore%20the%20Meteor%20platform%20in%20depth%5C%22%20which%20should%20probably%20link%20to%20the%20guide.%22%2C%20%22created_at%22%3A%20%222016-01-07T22%3A33%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/357702%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/mbrookes%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%20should%2C%20you%27re%20right%21%20Will%20do%20that%20soon.%22%2C%20%22created_at%22%3A%20%222016-01-07T22%3A33%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/meteor/guide/pull/186#issuecomment-169828474'>General Comment</a></b>
- <a href='https://github.com/mbrookes'></a> Incidentally, that page has a "Follow these links to explore the Meteor platform in depth" which should probably link to the guide.
- <a href='https://github.com/stubailo'></a> It should, you're right! Will do that soon.

<a href='https://www.codereviewhub.com/meteor/guide/pull/186?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/meteor/guide/pull/186?approve=1'></a>&nbsp;<a href='https://github.com/meteor/guide/pull/186'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by stubailo** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/meteor/guide/pull/186'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by mbrookes** [comment]
Incidentally, that page has a "Follow these links to explore the Meteor platform in depth" which should probably link to the guide.

**Comment by stubailo** [comment]
It should, you're right! Will do that soon.

**Comment by mbrookes** [comment]
Also, it's very well hidden on Meteor.com!

**Comment by stubailo** [comment]
Yeah, we are thinking of de-emphasizing these kinds of materials - they aren't particularly useful for developers because they don't actually tell you how to use the thing, and they aren't that useful for non-developers either. What do you think?

**Comment by mbrookes** [comment]
I kind of thought the opposite! I mean, I knew about all those things, if only through osmosis, but it was a really helpful read to have them all grouped together like that, and described in detail with the philosophy behind them, which is why I linked to it from here.

If I was to try and pitch it somewhere, I'd say it's useful background reading for a developer who's already covered the basics through the tutorial (or has built some basic apps themselves), and wants to understand what some of the tools they've been exposed to are designed to do, without reading the entire guide. Thinking about it, it could even be a section _in_ the guide.

**Comment by stubailo** [comment]
Yeah I think my main problem is that it's a bit long. And yeah, I think eventually that stuff should fit in the guide, perhaps in some sort of overview/concepts/philosophy section.

**Pull request merged**
