### PR TITLE
Use eslint-import-resolver

### PR DESCRIPTION
**Pull request by trajano**
Thanks for submitting a PR! We'll try to look at it as soon as possible.

If you are adding significant new content, please take a moment to include an update to the [changelog](https://github.com/meteor/guide/blob/master/CHANGELOG.md) in your PR.

Use this field to describe your pull request.

### CODE REVIEW

**Comment by trajano** [comment]
Use eslint-import-resolver

**Comment by tmeasday** [comment]
Looks great! Can we first test that it works against https://github.com/meteor/todos ?

**Comment by dburles** [comment]
This definitely should be in the guide! :)

**Comment by tmeasday** [comment]
Thanks! See #489

**Comment by abernix** [comment]
@dburles, @trajano: Given #489, can this be closed now?

You'll forgive some of these lint issues piling up here – I don't use these configurations so need input from the community in order to keep this issues moving along.  Your input is much appreciated.

**Comment by abernix** [comment]
I'm leaning toward closing this.  @dburles, @trajano?  (Apologies if you're busy).

**Pull request closed without merging**
