### PR TITLE
Flow Router Extra - Dynamic Module Loading

### PR DESCRIPTION
**Pull request by dr-dimitru**

### CODE REVIEW

**Comment by dr-dimitru** [comment]
From my point of view this is not final version of what is [discussed here](https://forums.meteor.com/t/urls-and-routing/19663/15) to be changed/added. I'm ready to push more changes upon request.

 1. If MDG agree on deprecation of original `flow-router` I'm ready to update all the docs replacing `flow-router` with `flow-router-extra`

//cc @stubailo

**Comment by abernix** [comment]
I thought `kadira:flowrouter` got adopted by someone else when Kadira put it up for grabs, did that never happen?

**Comment by dr-dimitru** [comment]
Hello @abernix ,

Here is [discussion](https://forums.meteor.com/t/what-a-best-alternative-for-flowrouter-now-after-lost-arunoda-and-kadira/31846/56) where I'm asking @arunoda for the merge, but seems our vision is too different. Actually @stubailo also mentioned `waitOn` as "one of the most confusing (and UX harming) parts of IR". Other fork authors also highlighted in this thread. As I see so far @arunoda didn't made a choice and latest commit to `master` is a more than a year old.

Speaking of what we have done to keep `flow-router`, see [releases](https://github.com/VeliovGroup/flow-router/releases), TL;TR;
 - Make sure it work with latest Meteor release, regularly update auto-tests
 - `dynamic import(...)` in `waitOn`
 - Add support for React + helpers for React
 - Build in rendering for Blaze, with respect to `requestAnimationFrame` (no FPS drops)
 - Build in `arillo:flow-router-helpers` and `zimme:active-route`, as both packages is stale for more than a year
 - Move all codebase to ES6
 - Fix most of the issues reported to original FR
 - Implement most of the fixes submitter as PRs to original FR

We can make smooth transition from `kadira:flow-router` to `ostrio:flow-router-extra` as old API remains the same and packages can be swapped by user with only codebase change: 
```js
import { FlowRouter } from 'meteor/ostrio:flow-router-extra';
```

@abernix let me know what do you think.

**Comment by dr-dimitru** [comment]
Go or no go?

**Comment by lorensr** [comment]
@abernix I can edit & merge this for now as an added option, not a replacement?

**Comment by abernix** [comment]
Even with the concerned raised about implementation in `waitOn`, I'm game for replacing the Guide recommendation to use `kadira:flow-router` with `ostrio:flow-router-extra` given the excellent work which that project has put forth in keeping it compatible with recent versions of Meteor.

**Comment by abernix** [comment]
I guess that begs the question of whether this PR is still in mergeable condition, as is?

**Comment by dr-dimitru** [comment]
@abernix 
If you mean to replace `kadira:flow-router` with `ostrio:flow-router-extra` in the guideline, I bet it's better to send new PR.
Let me know if we should describe how to use `waitOn` and/or other FR-Extra features.

**Comment by dr-dimitru** [comment]
@abernix any news?

**Comment by afrokick** [comment]
@dr-dimitru @filipenevola Is it right time to merge this PR?

**Pull request merged**
