### PR TITLE
Add example of making your own Cordova plugin

### PR DESCRIPTION
**Pull request by lorensr**
@martijnwalraven Just making sure this is what you meant? It works for me!

### CODE REVIEW

**Comment by lorensr** [comment]
Ah, I missed the new `navigation` option to `App.accessRule`. Is there another common purpose I can use for the plugin example?

**Comment by lorensr** [comment]
ping @martijnwalraven ☺️

**Comment by martijnwalraven** [comment]
Hmmm, not sure. Maybe adding permissions for Android?

**Comment by StorytellerCZ** [comment]
Hi @lorensr , I think this is pretty out of date at this stage so I'm going to close this. If you would like to update this or continue on this then feel free to re-open this. Also you might want to consider adding content like this to [Meteor examples](https://github.com/meteor/examples) or one of the tutorials.

**Pull request closed without merging**
