### PR TITLE
Mongodb hosting deployment

### PR DESCRIPTION
**Pull request by cfnelson**
Added more details to the `MongoDB hosting services to use with Galaxy` section of the guide.

**Changes made:**
 - Added recommendation for compose.io and MongoDB Atlas in addition to mLab
 - Added more details on features to look out for when selecting a hosting service
 - Added hyperlink to a step-by-step guide to setting up MongoDB Atlas for your Meteor app

I attempted to keep changes to a minimum, let me know if this is a significant change and I can update the CHANGELOG.md.

### CODE REVIEW

**Comment by stubailo** [comment]
Yeah this should definitely be in the changelog. A big reason we have that is so that people who haven't looked in a while can catch up on what has been added. This is great new information, so it should get a spot there.

**Comment by cfnelson** [comment]
@stubailo Added a short description to the Changelog. Let me know what else I need to do to get this merged. 😄

**Comment by stubailo** [comment]
LGTM. I think it's good that the linked article makes a comparison for people.

**Comment by cfnelson** [comment]
@stubailo Thanks for merging! 😄  Let me know if you would like something like the comparison in the Meteor guides. Will be happy to make further contributions to the MongoDB section.

**Comment by stubailo** [comment]
Personally I'd rather not have that directly inside because it's very easy for it to get outdated. I think the list of things to look for is perfect.

**Pull request merged**
