### PR TITLE
translation-de: Updated branch to latest commit in master

### PR DESCRIPTION
**Pull request by lightningboss**

### CODE REVIEW

**Comment by tmeasday** [comment]
This seems odd. Why is it not just a merge commit? Did you rebase or something?

**Comment by lightningboss** [comment]
This definetely seems odd. I'm going to take a look at it.

**Comment by abernix** [comment]
@lightningboss Any update on this?

**Comment by abernix** [comment]
Though it appears terrifyingly in the PR, I think this is actually correct since it's not a squash: one merge commit plus all the commits since the last merge.

Anyhow, I think this is stale enough at this point to close it.  Let's revisit in a new PR!

**Pull request closed without merging**
