### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tom-sockpuppet**
Thanks for submitting a PR! We'll try to look at it as soon as possible.

If you are adding significant new content, please take a moment to include an update to the [changelog](https://github.com/meteor/guide/blob/master/CHANGELOG.md) in your PR.

Use this field to describe your pull request.

### CODE REVIEW

**Comment by stubailo** [comment]
I'm so curious to know what this is

**Comment by tmeasday** [comment]
Did you notice how the contribute bot started working again?

**Comment by stubailo** [comment]
THANKS

was this just a test account for it?

**Comment by tmeasday** [comment]
Sure was ;)

**Comment by stubailo** [comment]
Damn I thought it was something cool about bots and editing readmes automatically.

**Pull request closed without merging**
