### PR TITLE
Update pr template

### PR DESCRIPTION
**Pull request by stubailo**
I'm tired of seeing the boilerplate text!

One thing that worked well for apollo-client was adding a checklist in the body: https://github.com/apollostack/apollo-client/blob/master/.github/PULL_REQUEST_TEMPLATE.md

What would we put in such a checklist?

### CODE REVIEW

**Comment by lorensr** [comment]
I agree, always takes me a second to be like what's going on, then
remember, then look down 😄
Either "If you are adding significant new content, please take a moment to
include an update to the changelog
<https://github.com/meteor/guide/blob/master/CHANGELOG.md> in your PR." or
nothing?
Mental tiring of seeing any kind of boilerplate at all versus having to
change changelog ourselves a little more often?
I'd go with nothing, but happy w wtv

**Comment by stubailo** [comment]
Curious what @tmeasday thinks

**Comment by tmeasday** [comment]
A change log checklist seems like a good start

**Comment by lorensr** [comment]
Suggested changes in commits ^

**Comment by stubailo** [comment]
Thanks!

**Pull request merged**
