### PR TITLE
Clarify importing/exporting from /imports

### PR DESCRIPTION
**Pull request by skirunman**

### CODE REVIEW

**Comment by skirunman** [comment]
See discussion https://forums.meteor.com/t/clarification-of-server-folders-in-1-3-suggested-import-structure/20267

**Comment by stubailo** [comment]
Glad to have this improvement, and looking forward to more that come from people's questions!

**Comment by jamiedumont** [comment]
Thanks for turning my query into a PR. At least it wasn't just me that didn't know...

**Comment by batjko** [comment]
Yea, good clarification, this one. :+1:

**Pull request merged**
