### PR TITLE
Add back in build tool default loading order rules

### PR DESCRIPTION
**Pull request by skirunman**
Thanks for submitting a PR! We'll try to look at it as soon as possible.

If you are adding significant new content, please take a moment to include an update to the [changelog](https://github.com/meteor/guide/blob/master/README.md#changelog) in your PR.

### CODE REVIEW

**Comment by skirunman** [comment]
This should fix #336

**Comment by skirunman** [comment]
This includes some cross reference changes to mobile.md. Probably need to confirm with @martijnwalraven that the `cordova-build-override/` directory still works.

**Comment by stubailo** [comment]
Yeah this looks great to me. I expect the build override still works, since that would be a big backcompat change and wasn't mentioned in http://guide.meteor.com/1.3-migration.html#breaking-changes-mobile

**Comment by stubailo** [comment]
Awesome work, this is a great new addition to the guide!

**Comment by martijnwalraven** [comment]
The `cordova-build-override` mechanism still works, but I didn't include it in the guide because I don't think it is ever a good solution and it can lead to a lot of trouble.

The problem is that is overrides complete files, so if you use it to write your own `config.xml` for example, you lose all configuration information set by the build process and by installed plugins, which will likely break your app. 

Cordova has a `<config-file>` tag as part of `plugin.xml` that allows you to selectively change parts of configuration files, including `config.xml`, so if you absolutely must make changes, the recommendation would be to write a dummy plugin.

**Comment by stubailo** [comment]
@martijnwalraven OK, sorry I merged that if it isn't recommended! Please change it back if you think it is best.

**Comment by martijnwalraven** [comment]
@stubailo: I've removed the recommendation to override `config.xml` and mentioned the plugin alternative in https://github.com/meteor/guide/commit/4397c437b4f5ea9adcdad47a71f0c69068db2f74.

**Pull request merged**
