### PR TITLE
Include some of the tools from Kadira

### PR DESCRIPTION
**Pull request by arunoda**
This PR is just for the discussion and not need for merging.

We've some great experience with performance monitoring of Meteor apps (and node apps). Also integration with some third party services like Librato Metrics.

So, we can specially work this chapter. Since I'd like to write stuff on this matter.
So, this the question?

* Is it okay to mention tools from Kadira? Like Kadira Profiler and FlameGraph viewer. 

> Even though, I run Kadira, I am happy to show how to integrate with other platforms. 

Looking forward for the feedback.

### CODE REVIEW

**Comment by tmeasday** [comment]
I think it's a good question. Perhaps we should rephrase as "what's our policy around commercial offerings?"

I think we'd be mad to not mention Kadira of course. But there is a spectrum of stuff with some spammy stuff at the other end (if you know what I mean). A written down policy would make it way easier than having to judge things on a case-by-case basis.

**Comment by arunoda** [comment]
Yeah. I get it. I don't want to over promote Kadira. For an example, if we wanna integrate with other analytics platforms, then we can mention Kadira. (since, we are mentioning production platforms here)

I think, it's harder to write a policy for this. Since we can PR's that'd be okay.

**Comment by tmeasday** [comment]
I didn't actually mean that you'd be spammy about Kadira, just that there's a spectrum of from "totally useful and everyone wants to know about it [e.g. Kadira] .. to .. "basically just spam" [some person's new consulting shop, say].

**Comment by arunoda** [comment]
That's okay. Sometimes I'm spammy too :) 
Shall I work on a more in depth outline for this?

**Comment by gabrielhpugliese** [comment]
I have a question that goes the way opposite of Kadira: How can I actually debug things locally without the website but with same capabilities? I like to understand how could I do on my own :)

**Comment by stubailo** [comment]
After some conversation with @rdickert, I think it makes sense to put Kadira in there as it's currently the best tool for doing a lot of this stuff in a deployed Meteor app. It's not about promoting or not promoting commercial tools, it's about telling people about the best way to do something, and representing today's reality.

**Comment by arunoda** [comment]
@gabrielhpugliese Basically, you need to instrument Meteor internals. Since it's JS it's not that hard to dive deep. But need care.

You can look at Kadira source code on how we do them. And also look at the [MeteorX](https://github.com/meteorhacks/meteorx) package.

**Comment by gabrielhpugliese** [comment]
Oh cool didn't know it was OSS. Thanks

**Comment by stubailo** [comment]
Oops - can you reopen this against the `master` branch?

**Comment by arunoda** [comment]
My intention was to open a discussion and raise this point. Anyway, we got answers.
Do we need to open a issue/PR again?

**Comment by stubailo** [comment]
No, probably not! Let me go and add it to the outline as a record.

**Comment by arunoda** [comment]
Okay.

**Comment by stubailo** [comment]
Here: 6a81f6280efa6a3145ef52d08380bc993d7abeae

**Comment by arunoda** [comment]
:+1:

**Pull request closed without merging**
