### PR TITLE
Add namespacing, styles import and general cleanup

### PR DESCRIPTION
**Pull request by skirunman**
Added in package namespacing info as I find this useful. Also, lots of general cleanup and grammar fixes. Finally, added in package style import info for both npm and meteor packages. I'd wait to push this until 1.3.2 is released and all the import syntax is double checked. 

It's been fun helping out on Guide, but this will likely be my last major PR.

### CODE REVIEW

**Comment by tmeasday** [comment]
Thanks so much for everything @skirunman.

We may need to separate out the CSS import stuff for the reasons I mentioned in the other PR. Let's wait too see how that conversation plays out.

**Comment by skirunman** [comment]
No worries, pull the changes in whatever works best for you. I added my 2 cents in the comments on https://github.com/meteor/guide/pull/362 about Guide versions, etc.

**Comment by skirunman** [comment]
@tmeasday @stubailo Do you guys want to merge this now that 1.3.2 is out. I'm 99% certain all the imports work as shown.

**Comment by tmeasday** [comment]
Great stuff!

**Pull request merged**
