### PR TITLE
Crosswalk no longer maintained

### PR DESCRIPTION
**Pull request by paulincai**
TODO:

- [ ] If this is a significant change, update [CHANGELOG.md](https://github.com/meteor/guide/blob/master/CHANGELOG.md)
- [ ] Use `<h2 id="foo">` instead of `## Foo` for headers
- [ ] Leave a blank line after each header

### CODE REVIEW

**Comment by abernix** [comment]
Maybe we should just remove the whole Crosswalk section altogether?

**Comment by paulincai** [comment]
I feel that would be the right way, however some build tips should be provided. I dumped the crosswalk and rely now on the web view alone and…disaster. I use the cheapest Android 5.1 in the market ( Lenovo A2010) and the 2017 Samsung A3. No difference. Same choppy sliding of a card from left to right. I need to re-write and eliminate some css animation or something. It is not really like “you just need Meteor” for an Android app development any more. You need some more knowledge and downgrading of UX.

**Comment by skirunman** [comment]
We did some analysis of dropping Crosswalk in our app and it still gives the best cross platform support in our opinion. I would not recommend dropping it entirely from documentation, yet, but the comment about the project not being supported going forward makes sense to me.

**Comment by abernix** [comment]
Thanks for the additional insight, @skirunman!

**Pull request merged**
