### PR TITLE
Changed SimpleSchema example to use newContext

### PR DESCRIPTION
**Pull request by LewisW**
As mentioned in the [SimpleSchema docs](https://github.com/aldeed/meteor-simple-schema#unnamed-validation-contexts), a context must be created in order to run validate.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/meteor/guide/pull/171%23issuecomment-166042171%22%2C%20%22https%3A//github.com/meteor/guide/pull/171%23issuecomment-166048634%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/meteor/guide/pull/171%23issuecomment-166042171%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40LewisW%3A%20Thank%20you%20for%20submitting%20a%20pull%20request%21%20%20%20%20%20%20%20%20%20%20%20Before%20we%20can%20merge%20it%2C%20%20%20%20%20%20%20%20%20%20%20you%27ll%20need%20to%20sign%20the%20Meteor%20Contributor%20Agreement%20here%3A%20%20%20%20%20%20%20%20%20%20%20https%3A//contribute.meteor.com/%22%2C%20%22created_at%22%3A%20%222015-12-20T00%3A42%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4250050%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/meteor-bot%22%7D%7D%2C%20%7B%22body%22%3A%20%22Not%20in%20newer%20versions%20of%20simple%20schema%20-%20what%20version%20are%20you%20using%3F%22%2C%20%22created_at%22%3A%20%222015-12-20T01%3A10%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/meteor/guide/pull/171#issuecomment-166042171'>General Comment</a></b>
- <a href='https://github.com/meteor-bot'></a> @LewisW: Thank you for submitting a pull request!           Before we can merge it,           you'll need to sign the Meteor Contributor Agreement here:           https://contribute.meteor.com/
- <a href='https://github.com/stubailo'></a> Not in newer versions of simple schema - what version are you using?

<a href='https://www.codereviewhub.com/meteor/guide/pull/171?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/meteor/guide/pull/171?approve=1'></a>&nbsp;<a href='https://github.com/meteor/guide/pull/171'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by stubailo** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/meteor/guide/pull/171'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by stubailo** [comment]
Not in newer versions of simple schema - what version are you using?

**Comment by stubailo** [comment]
Going to close this as the code works as-is in the example app.

**Comment by LewisW** [comment]
Sorry yes, it appears I'm using an older version.

**Pull request closed without merging**
