### PR TITLE
Add essential packages to Outline.md

### PR DESCRIPTION
**Pull request by mikeLspohn**
Personally, I've had to look in various places to find common packages that are used in most Meteor projects. I think a section outlining the most essential packages and where to find them would be helpful to people just coming to Meteor.

### CODE REVIEW

**Comment by stubailo** [comment]
All of these will be mentioned in other parts of the guide. I don't want to structure it by "here's a cool tech you might want to use" - it's more like "I want to have user accounts in my app, what do I need to know?"

1. Routing - we are recommending flow router, there's a rough draft of a routing guide in another issue
2. Moment - there will probably be something about displaying dates correctly, but really this is just  library; I don't think is a crucial part of the app building experience.
3. NPM - that should definitely be in there 100%!
4. Accounts UI - we'll probably mention accounts-ui for prototyping, then recommend [useraccounts](https://atmospherejs.com/useraccounts/core) for more serious projects.

**Comment by stubailo** [comment]
Thanks for the suggestions, btw!

**Comment by mikeLspohn** [comment]
Ahhh ok, cool! That makes sense. I didn't know about flow router or useraccounts, thanks for the tip!

**Comment by stubailo** [comment]
> I didn't know about flow router or useraccounts

One of the main reasons we're writing this thing! So that people can be aware of cool packages and Meteor features.

**Pull request closed without merging**
