### PR TITLE
Include password reset token expiration in breaking changes

### PR DESCRIPTION
**Pull request by alanning**
TODO:

- [ ] If this is a significant change, update [CHANGELOG.md](https://github.com/meteor/guide/blob/master/CHANGELOG.md)
- [ ] Use `<h2 id="foo">` instead of `## Foo` for headers
- [ ] Leave a blank line after each header

### CODE REVIEW

**Comment by lorensr** [comment]
Thanks! 🙌

Oh hey, that was for an issue I opened! 😄

**Comment by alanning** [comment]
Dude!  I know!   heh, was just laughing about that with my partners yesterday.  Caused us sooooo much trouble.  And I think you ran across it as part of the work on roles-restricted which we sponsored...

**Comment by lorensr** [comment]
Oops, sorry 😄😜

**Comment by alanning** [comment]
Nah, just ironic.  Was a good suggestion and change.

**Pull request merged**
