### PR TITLE
How to export a module variable in CoffeeScript

### PR DESCRIPTION
**Pull request by fknipp**
Maybe there might be better places in the guide to put this information, but it should be written somewhere.

### CODE REVIEW

**Comment by stubailo** [comment]
@fknipp can you add an entry to the changelog? https://github.com/meteor/guide#changelog

**Comment by fknipp** [comment]
You're welcome :)

**Comment by stubailo** [comment]
Thanks!

**Comment by GeoffreyBooth** [comment]
I just stumbled across this. This section is just wrong. The syntax is _not_ different in CoffeeScript; CoffeeScript supports the `import` and `export` keywords, nearly identically to ES2015. What this PR is referring to is CommonJS `module.exports`, though it’s confusing CommonJS’ global `exports` object with the `export` keyword in CoffeeScript/ES2015.

This was written up here: https://docs.meteor.com/packages/modules.html#CoffeeScript. Clearly that’s hard to find, so perhaps we can replace this section with a link to that one?

**Comment by abernix** [comment]
@GeoffreyBooth That sounds fine to me.  Can you do a PR or shall I?

**Comment by lorensr** [comment]
Thanks Geoffrey, fixed in abedc3bd1680e5ace0cbc18e77d032b38a630aa1

**Comment by GeoffreyBooth** [comment]
@lorensr Thanks for tackling this, I haven’t had time just yet. In that commit it looks like the `exports.Lists = ListsCollection 'lists'` example is still there, after the link you added. I would think that this should become `export Lists = new ListsCollection 'lists'` or similar, i.e. using the `export` keyword (and ES2015 modules) rather than `exports` (and CommonJS). Even for CoffeeScript I think we should be encouraging the `import` and `export` keywords, and ES2015 modules, over CommonJS. Backticks aren’t required anymore.

**Comment by lorensr** [comment]
Oops thanks, fixed!

**Pull request merged**
