### PR TITLE
Replace the use of _.each to [].forEach

### PR DESCRIPTION
**Pull request by Slava**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/meteor/guide/pull/123%23issuecomment-162070216%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/meteor/guide/pull/123%23issuecomment-162070216%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Sweeet%21%22%2C%20%22created_at%22%3A%20%222015-12-04T20%3A13%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/meteor/guide/pull/123#issuecomment-162070216'>General Comment</a></b>
- <a href='https://github.com/stubailo'></a> Sweeet!

<a href='https://www.codereviewhub.com/meteor/guide/pull/123?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/meteor/guide/pull/123?approve=1'></a>&nbsp;<a href='https://github.com/meteor/guide/pull/123'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by stubailo** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/meteor/guide/pull/123'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by stubailo** [comment]
Sweeet!

**Comment by stubailo** [comment]
Thanks to our dope continuous deployment, you'll see this live in 1 minute :]

**Comment by Slava** [comment]
dope

**Comment by yyx990803** [comment]
:sunglasses:

**Comment by tmeasday** [comment]
Is `forEach()` ok though? I think it fails in phantom...

**Comment by stubailo** [comment]
I think we need to do what we can to make it work, but I'm sure we use it in meteor core a lot now

**Comment by Slava** [comment]
Isn't it pollyfilled by js-core or something?

**Comment by tmeasday** [comment]
I feel like I tried it relatively recently but I could be wrong about that. Let me try...

**Comment by tmeasday** [comment]
Ok, it worked just fine.

**Comment by robfallows** [comment]
Adding the `es5-shim` package ensures this is polyfilled correctly. Seem to remember Ben made a point of this (in his devshop talk, maybe?)

**Comment by stubailo** [comment]
Yeah I think we're making a point of having all our official code snippets rely on `ecmascript` and `es5-shim` so that we can be looking towards the future rather than the past. Browser compatibility should be the computer's job, not the developer's.

**Comment by robfallows** [comment]
:+1:

**Pull request merged**
