### PR TITLE
Translation zh cn

### PR DESCRIPTION
**Pull request by laosb**
Not fully translated. But ready for merge.

### CODE REVIEW

**Comment by laosb** [comment]
In our origin repo, we use Travis CI to do automatic deploy to GitHub Pages, and use CNAME file to bind domain `guide-zh.ourmeteor.com` to GitHub Pages. These files is removed in commits from 5ee4d91 to 448159e.

Further translation commits will be commit into ourmeteor/guide-zh before this get merged and up running. When this works, I will redirect `guide-zh.ourmeteor.com` to the official guide in Chinese address and deprecate ourmeteor/guide-zh.

**Comment by tmeasday** [comment]
Live at http://guide.meteor.com/zh_cn/ !

**Comment by laosb** [comment]
@tmeasday Thank you! Anyway, there is no language switcher on the site, and more importantly, we don't have any patterns to deal with the continuous long-term development of translations. Ideally, I suggest having these rules:

* Each language(dialect) gets only one localization group as a GitHub Team, having write access to the translation branch.
* Each localization group has its own translation guidelines based on their language, and must have one native speaker in this language.
* Any translations are submitted as PRs, which can only be merged with at least 2 LGTMs from the localization group including 1 LGTM from a native speaker at least. (This can have some exceptions)

**Comment by tmeasday** [comment]
That sounds like something to work towards, but for now, let's just keep submitting PRs to the guide and myself or another guide maintainer will merge them.

We'll add a language switcher once we get a more complete translation in a language!

**Comment by laosb** [comment]
OK, we will continue to use `ourmeteor/guide-zh` as the primary repo for Chinese translations, and I will do a PR (maybe) weekly to push the commits in our repo to this.

BTW, can you ping us on GitHub when the Guide have some changes which may affect translations (e.g. new articles, code snippet updates) by @ourmeteor/local_zh_cn ? So we can rebase our tranlsation on time to avoid misunderstanding and outdates.

**Comment by lorensr** [comment]
Most changes would affect translations. I would just periodically look at /compare. Or if you only wanted to update on major changes, could wait for additions to changelog.

**Comment by laosb** [comment]
I will just go on a monthly merge from meteor/guide devel (or on meteor release), so that we won't be outdated too fast!

**Pull request merged**
